# -*- coding: utf-8 -*-
"""coqui-tts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14pZjcNcC6Ar2kCqykyY48-GbMjln6mG1
"""

!apt-get update
!apt-get install -y espeak-ng
!pip uninstall -y coqui-tts TTS gruut
!pip install coqui-tts[languages] --no-cache-dir

import torch
from TTS.api import TTS
from IPython.display import Audio

device = "cuda" if torch.cuda.is_available() else "cpu"

test_text = """
Hello there.

This is a test of the text to speech system. I want to see how natural this voice sounds, and whether it feels like a real human speaking.

Let’s try different types of sentences.

First, a simple sentence. The quick brown fox jumps over the lazy dog.

Now, something with numbers. In 2026, technology has advanced significantly. The temperature today is 23 degrees Celsius, and the time is 3:45 PM.

Let’s test pauses...
Short pause.
And now, a longer pause...

How does it handle questions? Does this sound natural to you?

Now I will try to express a bit of emotion.
I am really excited about how far this technology has come!
But sometimes, I wonder... can it truly replace human speech?

Finally, let’s end with a smooth closing sentence.

Thank you for listening to this test. Have a great day.
"""

def generatate_audio(text):
  tts = TTS(model_name="tts_models/en/ljspeech/fast_pitch").to(device)
  tts.tts_to_file(text=text, file_path="outputs/audio.wav")
  return "outputs/audio.wav"

audio1 = generatate_audio(test_text)

def generatate_audio_2(text):
    tts = TTS(model_name="tts_models/en/vctk/vits").to(device)

    # choose a speaker (important for quality)
    speaker = "p225"  # you can change this

    tts.tts_to_file(
        text=text,
        speaker=speaker,
        file_path="outputs2/audio2.wav"
    )

    return "outputs/audio.wav"

audio2 = generatate_audio_2(test_text)

Audio(audio1)

Audio(audio2)

