# -*- coding: utf-8 -*-
"""coqui-tts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14pZjcNcC6Ar2kCqykyY48-GbMjln6mG1
"""

!apt-get update
!apt-get install -y espeak-ng
!pip uninstall -y coqui-tts TTS gruut
!pip install coqui-tts[languages] --no-cache-dir
!pip install pydub

import torch
from TTS.api import TTS
from IPython.display import Audio
from pydub import AudioSegment
import re

device = "cuda" if torch.cuda.is_available() else "cpu"

def generatate_audio(text, audio_name, dir="AudioOutput"):
  tts = TTS(model_name="tts_models/en/ljspeech/fast_pitch").to(device)
  tts.tts_to_file(text=text, file_path=f"{dir}/{audio_name}.wav")
  return f"{dir}/{audio_name}.wav"

def generatate_audio_2(text, audio_name, dir="AudioOutput"):
    tts = TTS(model_name="tts_models/en/vctk/vits").to(device)

    # choose a speaker (important for quality)
    speaker = "p225"  # you can change this

    tts.tts_to_file(
        text=text,
        speaker=speaker,
        file_path=f"{dir}/{audio_name}.wav"
    )

    return f"{dir}/{audio_name}.wav"

def clean_text(text):
    # Remove extra whitespace and empty lines
    text = re.sub(r'\s+', ' ', text)

    # Remove unwanted characters (keep basic punctuation)
    text = re.sub(r'[^a-zA-Z0-9.,!?\'" ]+', '', text)

    return text.strip()

# 3. Handle long text (gTTS limit workaround)
def split_text(text, max_length=4000):
    chunks = []
    while len(text) > max_length:
        split_index = text.rfind(' ', 0, max_length)
        chunks.append(text[:split_index])
        text = text[split_index:]
    chunks.append(text)
    return chunks

# 1. Read file
with open("files/chapter3.txt", "r", encoding="utf-8") as file:
    text = file.read()

cleaned_text = clean_text(text)
chunks = split_text(cleaned_text)

for i, chunk in enumerate(chunks):
  print(f"{i} : {chunk}")

for i, chunk in enumerate(chunks):
    audio = generatate_audio(text=chunk, audio_name=f"output_part_{i}", dir="AudioOutput")
    print(f"audio saved {audio}")

combined = AudioSegment.empty()

for i in range(len(chunks)):
    audio = AudioSegment.from_mp3(f"AudioOutput/output_part_{i}.wav")
    combined += audio

combined.export("final_output.mp3", format="mp3")

