# -*- coding: utf-8 -*-
"""GTTS Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EG2y4W0KbpZaADkIoRgZZs3CjGyjmX0e
"""

!pip install gtts
!pip install pydub

from gtts import gTTS
from pydub import AudioSegment
import re

# 1. Read file
with open("chapter3.txt", "r", encoding="utf-8") as file:
    text = file.read()

def clean_text(text):
    # Remove extra whitespace and empty lines
    text = re.sub(r'\s+', ' ', text)

    # Remove unwanted characters (keep basic punctuation)
    text = re.sub(r'[^a-zA-Z0-9.,!?\'" ]+', '', text)

    return text.strip()

cleaned_text = clean_text(text)

# 3. Handle long text (gTTS limit workaround)
def split_text(text, max_length=4000):
    chunks = []
    while len(text) > max_length:
        split_index = text.rfind(' ', 0, max_length)
        chunks.append(text[:split_index])
        text = text[split_index:]
    chunks.append(text)
    return chunks

chunks = split_text(cleaned_text)

for i, chunk in enumerate(chunks):
  print(f"{i} : {chunk}")



# 4. Convert each chunk to audio
for i, chunk in enumerate(chunks):
    tts = gTTS(text=chunk, lang='en')
    tts.save(f"output_part_{i}.mp3")

print("Audio files generated successfully!")

combined = AudioSegment.empty()

for i in range(25):
    audio = AudioSegment.from_mp3(f"output_part_{i}.mp3")
    combined += audio

combined.export("final_output.mp3", format="mp3")

